# Generated by Django 5.1.7 on 2025-03-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usersapp', '0002_usermodel_delete_usersmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
