# Generated by Django 5.1.7 on 2025-03-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.EmailField(max_length=100)),
                ('start_data', models.DateTimeField(auto_now=True)),
                ('end_data', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='blog/')),
            ],
        ),
    ]
