# Generated by Django 5.1.7 on 2025-03-27 06:29

import Blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='content',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='end_data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(upload_to=Blog.models.rename_image),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='start_data',
            field=models.DateTimeField(),
        ),
    ]
