# Generated by Django 5.1.7 on 2025-03-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='product_id',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
