# Generated by Django 5.1.7 on 2025-03-28 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0002_alter_reviewmodel_data_alter_reviewmodel_product_id_and_more'),
        ('Usersapp', '0003_alter_usermodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usersapp.usermodel'),
        ),
    ]
