# Generated by Django 5.1.7 on 2025-04-02 11:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryApp', '0002_alter_subcategory_slug_and_more'),
        ('ProductApp', '0001_initial'),
        ('Promotion', '0002_alter_sale_options_sale_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sale',
            name='discount_range_check',
        ),
        migrations.RemoveConstraint(
            model_name='sale',
            name='end_after_start_check',
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='Promotion_s_start_d_cffb3b_idx',
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='Promotion_s_is_acti_0e9a3d_idx',
        ),
        migrations.AlterField(
            model_name='sale',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='CategoryApp.category'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='ProductApp.product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
