# Generated by Django 5.1.7 on 2025-03-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
