# Generated by Django 5.1.7 on 2025-03-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_remove_cartmodel_user_cartmodel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
