# Generated by Django 5.1.7 on 2025-03-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='product_id',
            field=models.CharField(max_length=1000),
        ),
    ]
