# Generated by Django 5.1.7 on 2025-03-28 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_ordermodel_product_id'),
        ('Usersapp', '0003_alter_usermodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usersapp.usermodel'),
        ),
    ]
